service: suu-backend

useDotenv: true

plugins: 
- serverless-offline

provider: 
name: aws
runtime: nodejs18.x
enviroment: 
PORT=7000

POSTGRES_HOST=localhost
POSTGRES_USER=postgres
POSTGRES_PASSWORD=root
POSTGRES_DB=nest-course
POSTGRES_PORT=5432

DEVPORT=4000

PRIVATE_KEY=botya_auth_secret_key

functions: 
main: 
handler: dist/serverless.handler
events: 
-http: 
method: ANY
path: /
-http: 
method: ANY
path: '{proxy+}'